### ISSUE TITLE
feat: React Native Web - Metro

### ISSUE THREAD

**Issue by soderalohastrom** [stagewise-io/stagewise#207]
### Describe the feature you'd like to request

Expo Web (Metro) support
---

## Steps to reproduce

1. Create a new Expo project (`npx create-expo-app`)
2. Install `@stagewise/toolbar-react` and `@stagewise/toolbar` as dev dependencies
3. Add the recommended integration code to `App.tsx` (or main entry)
4. Run `expo start --web`
5. Observe the bundler error

## Expected behavior

The Stagewise toolbar should load in development mode on Expo Web (React Native Web), just as it does in standard React web projects.

## Actual behavior

Metro cannot resolve the `@stagewise/toolbar` package, and the web build fails.

This appears to be due to the way the package exposes its entry points and/or its compatibility with Metro bundler. Standard React web projects (CRA, Vite, Next.js) work fine.

**Is Expo Web (Metro) support planned?**  
Any workarounds or timeline for compatibility would be appreciated!

### Describe the solution you'd like to see

Expo Web (Metro) support 

### Describe alternate solutions

Some workaround, or actual support for RNW Expo

### 👨‍👧‍👦 Contributing

- [ ] 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!

**Comment by jafri** [comment]
Fixed with

```
diff --git a/node_modules/@stagewise/toolbar/package.json b/node_modules/@stagewise/toolbar/package.json
index 9810400..482c59e 100644
--- a/node_modules/@stagewise/toolbar/package.json
+++ b/node_modules/@stagewise/toolbar/package.json
@@ -82,5 +82,7 @@
     "dev:examples": "tsc -b && vite build --mode development",
     "build:toolbar": "tsc -b && vite build --mode production",
     "build": "tsc -b && vite build --mode production"
-  }
+  },
+  "main": "./dist/index.umd.js",
+  "module": "./dist/index.es.js"
 }
\ No newline at end of file

```

**Comment by glenntws** [comment]
Awesome to see the fix @jafri ! Seems like some bundlers are still not compatible with the new export definitions.

@soderalohastrom We will incorporate this fix in the next release - by the way: It would be awesome to hear about your experience with stagewise in React Native. We never used it like that. Maybe you can join on Discord ( https://discord.gg/y8gdNb4D ) and we can have a chat about that? :)
